name: Test Minver and it's functionality

on:
  push:
    branches:
      - main
      - dev
      - first-branch

jobs:
  test-minver:
    runs-on: ubuntu-latest

    steps:
      - name: Extract Branch Name
        id: extract-git-branch-name
        run: |
          echo "ENVIRONMENT=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"

      - name: Install Minver
        id: install-minver
        run: |
          dotnet tool install --global minver-cli --version 6.0.0

      - name: Set minver version
        id: set-minver-version
        run: |
          VERSION=$(minver -p ${{ env.ENVIRONMENT }})
          echo VERSION >> $GITHUB_ENV

      - name: Check minver version
        id: check-minver-version
        run: |
          echo ${{ env.VERSION }}
